Introduction
https://laravel.com/docs/7.x/pagination

In other frameworks, pagination can be very painful. Laravel's paginator is integrated with the query builder and Eloquent ORM and provides convenient, easy-to-use pagination of database results out of the box. The HTML generated by the paginator is compatible with the Bootstrap CSS framework.


Basic Usage
  Paginating Query Builder Results
  Paginating Eloquent Results
  Manually Creating A Paginator
